apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-gyxe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-gyxe
    app.kubernetes.io/part-of: test-rhtap-56-app
  name: devfile-sample-code-with-quarkus-gyxe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-gyxe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-gyxe
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-56-tenant/test-rhtap-56-app/devfile-sample-code-with-quarkus-gyxe@sha256:96da8d59fa18ffefc60f0abcd1b71238bb08a146e8191b549434236492e496fe
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
